[package]
name = "launchpad_mini"
version = "0.1.0"
authors = ["flo <floriandavid.lange@web.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
midir = "0.7.0"